### ISSUE TITLE
basic setup fails on error "a branch named 'master' already exists"

### ISSUE THREAD

**Issue by spacewaffle** [robotology/gh-action-nightly-merge#4]
This is what my yaml file looks like. Notice checkout was bumped to v2. Not sure if that should change anything. Action is failing on the checkout which seems to make sense. Can't checkout a new branch called master if it already exists locally.

```
git fetch origin master
git checkout -b master origin/master
```

```
name: 'Auto Merge Master to Staging'

on:
  push:
    branches:
      - master

jobs:
  auto-merge-master-to-staging:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Merging Master Into Staging
      uses: robotology/gh-action-nightly-merge@v1.2.0
      with:
        development_branch: 'staging'
        allow_ff: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
