### ISSUE TITLE
The step success, but no merge has been made

### ISSUE THREAD

**Issue by ericknyoto** [robotology/gh-action-nightly-merge#6]
The process stopped after the message:

`Nightly merge action is disabled for forks (use the 'allow_forks' option to enable it).`

What cause this?

```
  'Nightly Merge Action' is using the following input:
    - stable_branch = 'master'
    - development_branch = 'integration-test'
    - allow_ff = false
    - allow_git_lfs = 
    - ff_only = false
    - allow_forks = false
    - user_name = GitHub Nightly Merge Action
    - user_email = actions@github.com
    - push_token = FOO_TOKEN = ***

Nightly merge action is disabled for forks (use the 'allow_forks' option to enable it).
```

This the YAML file:

```
- name: Sync INTEGRATION TEST
  uses: robotology/gh-action-nightly-merge@v1.3.2
  with:
    stable_branch: 'master'
    development_branch: 'integration-test'
    allow_ff: false
    push_token: 'FOO_TOKEN'
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    FOO_TOKEN: ${{ secrets.JG_BOT_TOKEN }}
```
